name: Deploy to Oracle Cloud

on:
  push:
    branches: ["main"]
    tags: ["v*"] # Triggers on tags like v1.0, v1.0.0, etc.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure Target Environment & Secrets
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "--- Deploying to PRODUCTION ---"
            echo "DEPLOY_PATH=/var/www/production" >> $GITHUB_ENV

            echo "ENV_CONTENT<<EOF" >> $GITHUB_ENV
            echo "${{ secrets.PRO_ENV_FILE }}" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          else
            echo "--- Deploying to DEVELOPMENT ---"
            echo "DEPLOY_PATH=/var/www/development" >> $GITHUB_ENV

            echo "ENV_CONTENT<<EOF" >> $GITHUB_ENV
            echo "${{ secrets.DEV_ENV_FILE }}" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "v25"
          cache: "npm"

      - name: Create .env file
        run: |
          echo "$ENV_CONTENT" > .env

      - name: Install pnpm
        run: |
          npm install -g pnpm

      - name: Install and Build
        run: |
          pnpm install
          pnpm run build

      - name: Copy files to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEVELOPMENT_HOST }}
          username: ${{ secrets.DEVELOPMENT_HOST_USERNAME }}
          key: ${{ secrets.DEVELOPMENT_HOST_SSH_PRIVATE_KEY }}
          source: "dist/*"
          target: ${{ env.DEPLOY_PATH }}
          strip_components: 1

      - name: Fix Permissions
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEVELOPMENT_HOST }}
          username: ${{ secrets.DEVELOPMENT_HOST_USERNAME }}
          key: ${{ secrets.DEVELOPMENT_HOST_SSH_PRIVATE_KEY }}
          script: |
            chmod -R 755 ${{ env.DEPLOY_PATH }}
